// Points data from the Munitorum Field Manual, and the arithmetic over it.
//
// data/ is generated by tools/sync-mfm.py from BSData/wh40k-11e-mfm. Faction
// files are fetched on demand and cached by the service worker, so a faction
// you have opened once stays available offline.

const cache = new Map();
const loaded = new Map();
let indexPromise = null;

/** Synchronous access to a faction already fetched by ensure(). */
export const got = (slug) => loaded.get(slug) || null;

/**
 * Fetch every named faction and keep it for synchronous use, so rendering does
 * not have to be async. A faction that fails to load stays absent, and the
 * views fall back to showing no points rather than breaking.
 */
export async function ensure(slugs) {
  const wanted = [...new Set(slugs.filter((s) => s && !loaded.has(s)))];
  await Promise.all(wanted.map((s) =>
    faction(s).then((f) => loaded.set(s, f)).catch(() => {})));
}

export function index() {
  if (!indexPromise) {
    indexPromise = fetch("./data/factions.json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error("http " + r.status))))
      .catch((e) => { indexPromise = null; throw e; });
  }
  return indexPromise;
}

export function faction(slug) {
  if (!slug) return Promise.resolve(null);
  if (!cache.has(slug)) {
    cache.set(slug, fetch("./data/" + encodeURIComponent(slug) + ".json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error("http " + r.status))))
      .catch((e) => { cache.delete(slug); throw e; }));
  }
  return cache.get(slug);
}

export const sheet = (fac, name) =>
  (fac && name && fac.units.find((u) => u.name === name)) || null;

export const detachment = (fac, name) =>
  (fac && name && fac.detachments.find((d) => d.name === name)) || null;

// The pricing band for the `copy`-th instance of a unit in an army. Datasheets
// can charge more for repeat selections ("Your 3rd+ Units Cost").
function band(sh, copy) {
  for (const p of sh.pricing) {
    if (copy >= p.from && (p.to === null || copy <= p.to)) return p;
  }
  return sh.pricing[0];
}

/**
 * Cost of a unit of `models` models, as the `copy`-th of its datasheet.
 *
 * A unit may hold any number between the listed sizes, but pays the cost of the
 * next size up, so 7 Intercessors cost the same as 10.
 */
export function cost(sh, models, copy = 1) {
  if (!sh || !sh.pricing.length) return null;
  const costs = band(sh, copy).costs;
  const max = costs[costs.length - 1];
  const pick = costs.find((c) => models <= c.m) || max;
  return {
    points: pick.p,
    sizes: costs.map((c) => c.m),
    max: max.m,
    exact: costs.some((c) => c.m === models),
    over: models > max.m,
  };
}

/** Every legal model count for a datasheet, at its base pricing band. */
export const sizes = (sh) => (sh ? sh.pricing[0].costs.map((c) => c.m) : []);

/**
 * Points for a collection of units, at base pricing. Repeat-selection
 * surcharges are a mustering rule, so a shelf of models is valued at face cost;
 * lists apply the thresholds properly via listCost.
 */
export function collectionCost(fac, units) {
  let points = 0, priced = 0;
  for (const u of units) {
    const c = cost(sheet(fac, u.sheet), u.models.length);
    if (c) { points += c.points; priced++; }
  }
  return { points, priced, unpriced: units.length - priced };
}

/**
 * Points for a list. Entries are costed in order so that repeat selections of
 * the same datasheet pick up their surcharge, and enhancements are added on top.
 */
export function listCost(fac, entries) {
  const seen = new Map();
  let units = 0, enhancements = 0;
  const rows = entries.map((e) => {
    const sh = sheet(fac, e.unit.sheet);
    const copy = (seen.get(e.unit.sheet) || 0) + 1;
    if (e.unit.sheet) seen.set(e.unit.sheet, copy);
    const c = sh ? cost(sh, e.unit.models.length, copy) : null;
    let enh = 0;
    if (e.enhancement) {
      const d = detachment(fac, e.detachment);
      const found = d && d.enhancements.find((x) => x.name === e.enhancement);
      if (found) enh = found.points;
    }
    if (c) units += c.points;
    enhancements += enh;
    return { points: (c ? c.points : 0) + enh, priced: !!c, copy, enh, over: !!(c && c.over) };
  });
  return { rows, units, enhancements, total: units + enhancements };
}

export const fmt = (n) => n.toLocaleString("en-GB");
